<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" ignored="0" total="12" passed="9">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="478" started-at="2019-08-13T14:56:25Z" finished-at="2019-08-13T14:56:26Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="478" started-at="2019-08-13T14:56:25Z" finished-at="2019-08-13T14:56:26Z">
      <class name="com.revature.entitiestests.ModuleTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.revature.entitiestests.ModuleTest@4206a205]" name="setup" is-config="true" duration-ms="15" started-at="2019-08-13T14:56:25Z" finished-at="2019-08-13T14:56:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="testEqualsObject()[pri:0, instance:com.revature.entitiestests.ModuleTest@4206a205]" name="testEqualsObject" duration-ms="428" started-at="2019-08-13T14:56:25Z" finished-at="2019-08-13T14:56:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[EqualsVerifier found a problem in class Module.
-> Subclass: object is not equal to an instance of a trivial subclass with equal fields:
  Module [id=1, subject=one, created=1969-12-31 18:00:01.337, links=[Link [id=1, contentId=1, moduleId=1, affiliation=one]]]
Maybe you forgot to add usingGetClass(). Otherwise, consider making the class final.

For more information, go to: http://www.jqno.nl/equalsverifier/errormessages]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: EqualsVerifier found a problem in class Module.
-> Subclass: object is not equal to an instance of a trivial subclass with equal fields:
  Module [id=1, subject=one, created=1969-12-31 18:00:01.337, links=[Link [id=1, contentId=1, moduleId=1, affiliation=one]]]
Maybe you forgot to add usingGetClass(). Otherwise, consider making the class final.

For more information, go to: http://www.jqno.nl/equalsverifier/errormessages
at nl.jqno.equalsverifier.EqualsVerifierApi.verify(EqualsVerifierApi.java:305)
at com.revature.entitiestests.ModuleTest.testEqualsObject(ModuleTest.java:105)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: nl.jqno.equalsverifier.internal.exceptions.AssertionException
at nl.jqno.equalsverifier.internal.util.Assert.assertTrue(Assert.java:54)
at nl.jqno.equalsverifier.internal.checkers.HierarchyChecker.checkSubclass(HierarchyChecker.java:136)
at nl.jqno.equalsverifier.internal.checkers.HierarchyChecker.check(HierarchyChecker.java:46)
at nl.jqno.equalsverifier.EqualsVerifierApi.verifyWithExamples(EqualsVerifierApi.java:380)
at nl.jqno.equalsverifier.EqualsVerifierApi.performVerification(EqualsVerifierApi.java:350)
at nl.jqno.equalsverifier.EqualsVerifierApi.verify(EqualsVerifierApi.java:302)
... 26 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testEqualsObject -->
        <test-method status="FAIL" signature="testGetCreated()[pri:0, instance:com.revature.entitiestests.ModuleTest@4206a205]" name="testGetCreated" duration-ms="2" started-at="2019-08-13T14:56:26Z" finished-at="2019-08-13T14:56:26Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at com.revature.entitiestests.ModuleTest.testGetCreated(ModuleTest.java:72)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetCreated -->
        <test-method status="PASS" signature="testGetId()[pri:0, instance:com.revature.entitiestests.ModuleTest@4206a205]" name="testGetId" duration-ms="1" started-at="2019-08-13T14:56:26Z" finished-at="2019-08-13T14:56:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetId -->
        <test-method status="PASS" signature="testGetLinks()[pri:0, instance:com.revature.entitiestests.ModuleTest@4206a205]" name="testGetLinks" duration-ms="1" started-at="2019-08-13T14:56:26Z" finished-at="2019-08-13T14:56:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetLinks -->
        <test-method status="PASS" signature="testGetSubject()[pri:0, instance:com.revature.entitiestests.ModuleTest@4206a205]" name="testGetSubject" duration-ms="0" started-at="2019-08-13T14:56:26Z" finished-at="2019-08-13T14:56:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetSubject -->
        <test-method status="PASS" signature="testModule()[pri:0, instance:com.revature.entitiestests.ModuleTest@4206a205]" name="testModule" duration-ms="0" started-at="2019-08-13T14:56:26Z" finished-at="2019-08-13T14:56:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testModule -->
        <test-method status="PASS" signature="testModuleIntStringIntSetOfLink()[pri:0, instance:com.revature.entitiestests.ModuleTest@4206a205]" name="testModuleIntStringIntSetOfLink" duration-ms="1" started-at="2019-08-13T14:56:26Z" finished-at="2019-08-13T14:56:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testModuleIntStringIntSetOfLink -->
        <test-method status="FAIL" signature="testSetCreated()[pri:0, instance:com.revature.entitiestests.ModuleTest@4206a205]" name="testSetCreated" duration-ms="1" started-at="2019-08-13T14:56:26Z" finished-at="2019-08-13T14:56:26Z">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at com.revature.entitiestests.ModuleTest.testSetCreated(ModuleTest.java:78)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetCreated -->
        <test-method status="PASS" signature="testSetId()[pri:0, instance:com.revature.entitiestests.ModuleTest@4206a205]" name="testSetId" duration-ms="0" started-at="2019-08-13T14:56:26Z" finished-at="2019-08-13T14:56:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetId -->
        <test-method status="PASS" signature="testSetLinks()[pri:0, instance:com.revature.entitiestests.ModuleTest@4206a205]" name="testSetLinks" duration-ms="0" started-at="2019-08-13T14:56:26Z" finished-at="2019-08-13T14:56:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetLinks -->
        <test-method status="PASS" signature="testSetSubject()[pri:0, instance:com.revature.entitiestests.ModuleTest@4206a205]" name="testSetSubject" duration-ms="0" started-at="2019-08-13T14:56:26Z" finished-at="2019-08-13T14:56:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSetSubject -->
        <test-method status="PASS" signature="testToString()[pri:0, instance:com.revature.entitiestests.ModuleTest@4206a205]" name="testToString" duration-ms="1" started-at="2019-08-13T14:56:26Z" finished-at="2019-08-13T14:56:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testToString -->
      </class> <!-- com.revature.entitiestests.ModuleTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
